name: Release
on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: "1.17"
  GH_USER: "aqua-bot"
jobs:
  manifest:
    name: Docker Manifests
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.183.0
          args: release --config goreleaser.manifests.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
